service: bemostudio
app: bemostudio-api
org: contactobemostudio

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  playground:
    handler: src/handlers/hanlder.playground
    events:
      - http:
        path: playground
        method: get
  query:
    handler: src/handlers/handler.query
    events:
      - http:
          path: query
          method: get
